# Lab | Not hot songs

In [1]:
import pandas as pd

Load the Kaggle dataset

In [2]:
df = pd.read_csv("dataset.csv")
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

Make sure that there are different song genres in the dataset

In [3]:
df['track_genre'].value_counts()

acoustic             1000
punk-rock            1000
progressive-house    1000
power-pop            1000
pop                  1000
                     ...
folk                 1000
emo                  1000
electronic           1000
electro              1000
world-music          1000
Name: track_genre, Length: 114, dtype: int64

Create a new dataframe with the columns that are needed

In [4]:
not_hot_songs = df[['track_name','artists']]
not_hot_songs

                        track_name                 artists
0                           Comedy             Gen Hoshino
1                 Ghost - Acoustic            Ben Woodward
2                   To Begin Again  Ingrid Michaelson;ZAYN
3       Can't Help Falling In Love            Kina Grannis
4                          Hold On        Chord Overstreet
...                            ...                     ...
113995         Sleep My Little Boy           Rainy Lullaby
113996            Water Into Light           Rainy Lullaby
113997              Miss Perfumado           CesÃ¡ria Evora
113998                     Friends        Michael W. Smith
113999                   Barbincor           CesÃ¡ria Evora

[114000 rows x 2 columns]

In [5]:
not_hot_songs.isna().value_counts()

track_name  artists
False       False      113999
True        True            1
dtype: int64

Drop the rows with null values. There are enough rows, so we can drop those rows without the dataset becoming too small

In [6]:
not_hot_songs.dropna(subset=['track_name'], inplace=True)
not_hot_songs

C:\Users\laura\AppData\Local\Temp\ipykernel_16080\3176810226.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_hot_songs.dropna(subset=['track_name'], inplace=True)

                        track_name                 artists
0                           Comedy             Gen Hoshino
1                 Ghost - Acoustic            Ben Woodward
2                   To Begin Again  Ingrid Michaelson;ZAYN
3       Can't Help Falling In Love            Kina Grannis
4                          Hold On        Chord Overstreet
...                            ...                     ...
113995         Sleep My Little Boy           Rainy Lullaby
113996            Water Into Light           Rainy Lullaby
113997              Miss Perfumado           CesÃ¡ria Evora
113998                     Friends        Michael W. Smith
113999                   Barbincor           CesÃ¡ria Evora

[113999 rows x 2 columns]

Rename the songs column

In [7]:
not_hot_songs.rename(columns={'track_name': 'Song','artists':'Artist'}, inplace=True)
not_hot_songs

C:\Users\laura\AppData\Local\Temp\ipykernel_16080\253226804.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_hot_songs.rename(columns={'track_name': 'Song','artists':'Artist'}, inplace=True)

                              Song                  Artist
0                           Comedy             Gen Hoshino
1                 Ghost - Acoustic            Ben Woodward
2                   To Begin Again  Ingrid Michaelson;ZAYN
3       Can't Help Falling In Love            Kina Grannis
4                          Hold On        Chord Overstreet
...                            ...                     ...
113995         Sleep My Little Boy           Rainy Lullaby
113996            Water Into Light           Rainy Lullaby
113997              Miss Perfumado           CesÃ¡ria Evora
113998                     Friends        Michael W. Smith
113999                   Barbincor           CesÃ¡ria Evora

[113999 rows x 2 columns]

Load the Billboard Top 100 csv

In [8]:
billboard_top_100 = pd.read_csv("../../Morning/lab-web-scraping-single-page/billboard_top_100.csv")
billboard_top_100.head()

         Song               Artist
0     Vampire       Olivia Rodrigo
1  Last Night        Morgan Wallen
2    Fast Car           Luke Combs
3   Calm Down  Rema & Selena Gomez
4     Flowers          Miley Cyrus

Find the songs that are both in the Billboard Top 100 and the Kaggle dataset

In [9]:
already_present_songs = pd.merge(not_hot_songs, billboard_top_100, on=['Song','Artist'])
already_present_songs

                  Song         Artist
0            You Proof  Morgan Wallen
1  Next Thing You Know   Jordan Davis

Drop the rows that contain the songs that are in the Billboard Top 100

In [10]:
not_hot_songs.drop(not_hot_songs[(not_hot_songs['Song'] == 'You Proof') & (not_hot_songs['Artist'] == 'Morgan Wallen')].index, inplace = True)
not_hot_songs.drop(not_hot_songs[(not_hot_songs['Song'] == 'Next Thing You Know') & (not_hot_songs['Artist'] == 'Jordan Davis')].index, inplace = True)
not_hot_songs

C:\Users\laura\AppData\Local\Temp\ipykernel_16080\3187685602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_hot_songs.drop(not_hot_songs[(not_hot_songs['Song'] == 'You Proof') & (not_hot_songs['Artist'] == 'Morgan Wallen')].index, inplace = True)
C:\Users\laura\AppData\Local\Temp\ipykernel_16080\3187685602.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  not_hot_songs.drop(not_hot_songs[(not_hot_songs['Song'] == 'Next Thing You Know') & (not_hot_songs['Artist'] == 'Jordan Davis')].index, inplace = True)

                              Song                  Artist
0                           Comedy             Gen Hoshino
1                 Ghost - Acoustic            Ben Woodward
2                   To Begin Again  Ingrid Michaelson;ZAYN
3       Can't Help Falling In Love            Kina Grannis
4                          Hold On        Chord Overstreet
...                            ...                     ...
113995         Sleep My Little Boy           Rainy Lullaby
113996            Water Into Light           Rainy Lullaby
113997              Miss Perfumado           CesÃ¡ria Evora
113998                     Friends        Michael W. Smith
113999                   Barbincor           CesÃ¡ria Evora

[113997 rows x 2 columns]

Save the dataframe to csv

In [11]:
not_hot_songs.to_csv('not_hot_songs.csv', index=False)